version: '3.3'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    environment:
      - PHPIDS_ENABLE=false
    volumes:
      - dvwa_data:/app
    restart: always

  mysql:
    image: mysql:5.7
    container_name: dvwa_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always


  nginx:
    image: owasp/modsecurity-crs:nginx
    container_name: nginx_waf
    ports:
      - "8081:8080"
    environment:
      - BACKEND=http://dvwa:80
      - PARANOIA=4
    depends_on:
      - dvwa
    restart: always

volumes:
  dvwa_data:
  mysql_data: